/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Arista Duran Yaxkin Raul
 */
public class CLAVE extends javax.swing.JFrame {

    /**
     * Creates new form CLAVE
     */
    private String txt;
    public CLAVE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn512 = new javax.swing.JButton();
        btn1024 = new javax.swing.JButton();
        btn2048 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 147, 72));
        setForeground(new java.awt.Color(255, 147, 72));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SELECCIONE LA LONGITUD DE BITS DE LA");

        btn512.setBackground(new java.awt.Color(255, 51, 255));
        btn512.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn512.setText("512");
        btn512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn512ActionPerformed(evt);
            }
        });

        btn1024.setBackground(new java.awt.Color(255, 51, 255));
        btn1024.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1024.setText("1024");
        btn1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1024ActionPerformed(evt);
            }
        });

        btn2048.setBackground(new java.awt.Color(255, 51, 255));
        btn2048.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn2048.setText("2048");
        btn2048.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2048ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("PARA SU CIFRADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn512)
                            .addComponent(btn1024)
                            .addComponent(btn2048))
                        .addGap(223, 223, 223))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(btn512)
                .addGap(29, 29, 29)
                .addComponent(btn1024)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btn2048)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>                        

    public void setTexto(String txt){
        this.txt = txt;
    }
    private void btn512ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        resultado res = new resultado();
        res.setLLave(512, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }                                      

    private void btn1024ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        resultado res = new resultado();
        res.setLLave(1024, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }                                       

    private void btn2048ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        resultado res = new resultado();
        res.setLLave(2048, txt);
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JButton btn1024;
    private javax.swing.JButton btn2048;
    private javax.swing.JButton btn512;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
